from tkinter import*
a=Tk()
a.title("entry form")
a.config(bg="yellow")
a.geometry("500x500")
msg=Message(a,text="WELCOME")
msg.pack(fill="x")
l=Label(a,text="hello",bg="yellow",fg="blue",font=("algerian",36))
l.pack(fill="x")
n=Label(a,text="name",fg="blue",font=("algerian",12))
n.place(x=90,y=80)
m=Entry(a,border=4)
m.place(x=200,y=80)
o=Label(a,text="players",fg="blue",font=("algerian",12))
o.place(x=90,y=130)
p=Listbox(a)
p.insert(1,"pre graduate")
p.insert(2,"graduate")
p.insert(3,"post graduate")
p.place(x=200,y=130)

a.mainloop()
